### ISSUE TITLE
[BUG] Update to 4.0.1 completely breaks website, links lead to different pages

### ISSUE THREAD

**Issue by SerinitySW** [linuxserver/docker-grocy#73] opened 2023-08-10 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When updating from 4.0.0 to 4.0.1, the website completely breaks. Links lead to other pages, chores are unable to be tracked, and half of the sidebar links lead to a barcode displayed on the screen. It also breaks API connections to the Grocy android app.

### Expected Behavior

Functional website as in 4.0.0

### Steps To Reproduce

1. In unRAID, update to the latest image (4.0.1)
2. Website no longer functions normally

### Environment

```markdown
- OS: unRAID
- How docker service was installed: Community Appstore
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
`[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│            │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-06-24 │ /config/nginx/ssl.conf                                                 │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
`
```

**Comment by SerinitySW** [comment] 2023-08-10 17:55
Downgrading back to 4.0.0 resolves the website issues.

**Comment by andreasbrett** [comment] 2023-08-12 09:48
duplicate of https://github.com/linuxserver/docker-grocy/issues/72

**Closed** 2023-09-25 17:06 UTC
Labels: no-issue-activity
