### ISSUE TITLE
502 Bad Gateway using raspberry pi 3b+ 64bit

### ISSUE THREAD

**Issue by adrigrillo** [linuxserver/docker-grocy#53] opened 2021-11-18 09:09 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Grocy webpage loads and expected, so the user can access to its account.

## Current Behavior
When the user tries to connect to Grocy, going to `localhost:9283` the browser returns an error 502 Bad Gateway produced by nginx.
This error can also be related with https://github.com/hassio-addons/addon-grocy/issues/224 and it seems that it is a problem with the alpine Linux image. 

## Steps to Reproduce

1. Install docker and docker compose in the Raspberry Pi 3B+.
2. Copy the example `compose.yml` from the README of this repo.
3. Start the image using docker compose, `docker-compose up -d`.
4. Access to Grocy webpage.

## Environment
**OS:** Debian 11 Bullseye
**CPU architecture:** arm64
**How docker service was installed:**

Using the installation script available in the official docker webpage. Additionally, following [this tutorial](https://phoenixnap.com/kb/docker-on-raspberry-pi).

The docker compose was installed using your [own tutorial](https://docs.linuxserver.io/general/docker-compose) following the recommended first method.

## Command used to create docker container (run/create/compose/screenshot)

Using the following compose.yml

```yaml
version: "2.1"
services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/adrigrillo/data/grocy-data-2:/config
    ports:
      - 9283:80
    restart: unless-stopped
```

and `docker-compose up -d`

## Docker logs

```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
_         ()
| |  ___   _    __  
| | / __| | |  /  \ 
| | \__ \ | | | () |      
|_| |___/ |_|  \__/
Brought to you by linuxserver.io 
-------------------------------------
To support LSIO projects visit: 
https://www.linuxserver.io/donate/ 
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000 
User gid:    1000 
-------------------------------------   
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0. 
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
....................................................................+++++
....................+++++ 
-----
writing new private key to '/config/keys/cert.key'   
[cont-init.d] 30-keygen: exited 0. 
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0. 
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0. 
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting... 
[cont-init.d] 99-custom-files: exited 0. 
[cont-init.d] done.
[services.d] starting services 
[services.d] done. 
```

However in the NGINX logs we can found:
- For the access.log
```
192.168.1.128 - - [18/Nov/2021:09:07:05 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.1.128 - - [18/Nov/2021:09:07:05 +0000] "GET /favicon.ico HTTP/1.1" 502 157 "http://192.168.1.191:9283/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0"
```

- For the error.log1
```
2021/11/18 09:07:05 [error] 368#368: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.128, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.191:9283"
2021/11/18 09:07:05 [error] 368#368: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.128, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.191:9283", referrer: "http://192.168.1.191:9283/"
```

**Comment by adrigrillo** [comment] 2021-11-18 09:45
I have been testing several images version, as Grocy was working until yesterday. 
The first image I manage to get it to start properly was the one with the tag ` v3.1.0-ls116` which is the first that does not use Alpine 3.14 and PHP 8.
It is possible that the Alpine and PHP and other dependencies use the latest version available, even the image was published some days ago?

**Comment by adrigrillo** [comment] 2021-11-18 16:12
Investigating more, I discovered if I go to the `/login` page and try to sign in with user admin and password admin, the following error is raised:

![imagen](https://user-images.githubusercontent.com/18198342/142453027-7a81543a-9c55-4420-a9a7-b125c55c8a68.png)

**Comment by unite42** [comment] 2021-12-09 22:43
I have the same problem. Followed the installation instructions for a new installation on a Raspberry Pi 3B+ and got the same errors.
Tried to find the reason but didn't find a solution yet.

**Comment by dersven98** [comment] 2022-02-07 03:42
i started an docker container on the latest version today, and i get on all ports (80, 443, 9830) an `Bad Gateway`
**the image is not working.**

**Comment by mathmaniac43** [comment] 2022-03-10 12:53
This is still not working.

**Comment by 404alex** [comment] 2022-04-03 18:59
It seems like the docker-compose example is wrong. At least in my test, it is listening on 80 and 443 instead of 9283.

**Comment by aptalca** [comment] 2022-04-03 19:40
9283 is the host port that is mapped to 80 inside the container

**Comment by 404alex** [comment] 2022-04-03 19:42
> 9283 is the host port that is mapped to 80 inside the container

I wasn't using port mapping. I was using macvlan, so I commented out the port mapping part. And I was not able to access it over 9283, but I was able to over 80 and 443.

**Comment by aptalca** [comment] 2022-04-03 19:50
If you didn't use the compose yaml we provided as is, how can you claim it's wrong?

**Comment by 404alex** [comment] 2022-04-03 20:05
> 

Here is the compose file I was using:

```yaml
version: "2.1"
services:
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - grocy_config:/config
    restart: unless-stopped
    network_mode: "macvlan"
    
volumes:
  grocy_config:
    external: true
```

I was trying to access through port 9283. But got refused connection. Then I ssh into the docker and run netstat -a:

```bash
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:https           0.0.0.0:*               LISTEN      
tcp        0      0 127.0.0.11:37625        0.0.0.0:*               LISTEN      
tcp        0      0 localhost:9000          0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN    
```

It seems like the docker is listening on port 80 and 443. Then I tried to access 80, got the grocy login page.

Therefore, I suspected the port should be 80:80 instead of 9283:80.

**Comment by aptalca** [comment] 2022-04-03 21:12
I think you should read up on port mapping: https://docs.docker.com/config/containers/container-networking/

**Comment by 404alex** [comment] 2022-04-03 21:16
Gotcha, sorry for misunderstood.
________________________________

**Comment by franciscobeltran** [comment] 2022-04-11 22:27
I have tried today to use the docker-compose of the example on my Raspberry Pi 3B+ and it still gives the same error. Bad Gateway 502 appears on both port 80 and 443.

**Comment by steiditi** [comment] 2022-04-20 07:35
I have the same issue, but after updating. I tried to update, because my grocy app wanted a newer version of the server. After updating I get 502 Bad Gateway nginx/1.20.2 . 
Also running on raspberry pi 3b+ with ubuntu 64bit.

**Comment by steiditi** [comment] 2022-04-21 17:41
Just to mention it. I took the SD Card and put it into a pi4. Everything works just fine there. No Error anymore.

**Comment by Krusty27** [comment] 2022-05-09 21:24
This still occurs, any workaround?

**Comment by norweeg** [comment] 2022-06-04 18:02
oh boy... came here to open this bug, but I see it's been open for a while...  It's still broken

**Comment by techano** [comment] 2022-06-07 10:14
Just spun this up on a pi 3b+ and still has this issue ongoing. Thought it was my setup for a second!

**Comment by lghtcrss** [comment] 2022-06-14 10:28
I have tried today to use the docker-compose of the example on my Raspberry Pi 3B+ and it still gives the same error. Bad Gateway 502 appears.

**Comment by lghtcrss** [comment] 2022-06-16 13:29
Unfortunately the latest image with the tag `linuxserver/grocy:v3.3.1-ls152@sha256:6e38ea35af9470f33a11966078b2a0c33b8f361cc51a8397135c34521a981f40` produces the same `Bad Gateway 502` error.

**Comment by norweeg** [comment] 2022-06-17 13:32
according to https://github.com/hassio-addons/addon-grocy/issues/197#issuecomment-879330485 the problem is an upstream problem in alpine's libxml2 package that has since been resolved.  When was the last time baseimage-alpine-nginx was built??  This problem would be present in any other images based on that base image.  I think if you were to rebuild baseimage-alpine-nginx, then rebuilt all images based on it, including the grocy image, that the problem would be resolved

**Comment by norweeg** [comment] 2022-06-27 13:38
Is this project actively maintained?  I get that its a volunteer effort, but this issue has a clear-cut upstream cause with a simple fix with a very small PR that resolves it.  over 10 days seems excessive to review such a small PR to resolve an issue that's existed since last year.

**Comment by Roxedus** [comment] 2022-06-27 14:02
It is. We currently have our 3.15 nginx base image on hold due to pending rework

**Comment by mathmaniac43** [comment] 2022-08-24 10:54
This issue is still relevant, and there is a pending MR to resolve when the maintainers have an opportunity.

**Comment by norweeg** [comment] 2022-09-09 14:31
this bug is still present in the latest release because it is still based on the same base image containing the upstream libxml2 bug

**Comment by norweeg** [comment] 2022-10-16 17:18
I just tested `lspipepr/grocy:v3.3.1-pkg-e772ab19-pr-52` on my Pi 3 and all is working

**Comment by nemchik** [comment] 2022-10-19 13:48
Closing this now that https://github.com/linuxserver/docker-grocy/pull/52 is merged. There should be a new release shortly.

**Closed by nemchik** 2022-10-19 13:48 UTC
